Models/ClassAttend.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Studenti.Models
{
    public class ClassAttend
    {
        [Key]
        public int Id { get; set; }
        public string IdentityUserId { get; set; }
        public DateTime LoggedTime { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        

        public ClassAttend(string identityUserId, string name, string surname, DateTime loggedTime)
        {
            IdentityUserId = identityUserId;
            Name = name;
            Surname = surname;
            LoggedTime = loggedTime;
         
            
        }
    }
}

Controllers/ClassAttendsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Studenti.Data;
using Studenti.Models;
using Studenti.Utility;

namespace Studenti.Controllers
{
    public class ClassAttendsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Korisnik> _userManager;

        public class DisplayAttend
        {
            public string JMBAG { get; set; }
            public DateTime LoggedTime { get; set; }

            public string Name { get; set; }
            public string Surname { get; set; }


         
            public DisplayAttend()
            {

            }

            public DisplayAttend(string name, string surname, string jMBAG, DateTime loggedTime )
            {
                JMBAG = jMBAG;
                Name = name;
                Surname = surname;
                LoggedTime = loggedTime;
             
         
            }

           
          

            
        }

        public ClassAttendsController(ApplicationDbContext context, UserManager<Korisnik> userManager)
        {
            _context = context;
            _userManager = userManager;
          
          
        }


      


        // GET: ClassAttends
        public async Task<IActionResult> Index()
        {
           var UserList = await _userManager.Users.ToListAsync();
            var currentUser = await _userManager.GetUserAsync(User);
            bool isStudent = await _userManager.IsInRoleAsync(currentUser, StaticDetails.StudentRole);
            List<ClassAttend> classAttends = null;
            
            if (isStudent)
            {   
                classAttends = await _context.ClassAttends.Where(ca => ca.IdentityUserId == currentUser.Id).ToListAsync();
               
               
            }
            else {

                classAttends = await _context.ClassAttends.ToListAsync();
            }

           List<DisplayAttend> data = new List<DisplayAttend>();

            foreach (ClassAttend ca in classAttends)
            {
                data.Add(new DisplayAttend(UserList.FirstOrDefault(u => u.Id == ca.IdentityUserId).Name, UserList.FirstOrDefault (u=> u.Id == ca.IdentityUserId).Surname, UserList.FirstOrDefault(u => u.Id == ca.IdentityUserId).JMBAG, ca.LoggedTime));


            }
            
            return View(data);
        }

        // POST: ClassAttends/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string t)
        {

            var currentUser = await _userManager.GetUserAsync(User);

            ClassAttend classAttend = new ClassAttend(currentUser.Id, currentUser.Name, currentUser.Surname, DateTime.Now);

            if (ModelState.IsValid)
            {
                _context.Add(classAttend);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(classAttend);
        }


       
    }
    }

Controllers/KorisniksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Studenti.Data;
using Studenti.Models;
using Studenti.Controllers;

namespace Studenti.Controllers
{
    public class KorisniksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public KorisniksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Korisniks
        public async Task<IActionResult> Index(string searchString)

        {
           
            ViewData["CurrentFilter"] = searchString;

         
            var li = from s in _context.Korisnik
                     select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                li = li.Where(s => s.Name.Contains(searchString)
                                       || s.Surname.Contains(searchString));
            }

           
        
            return View(await li.AsNoTracking().ToListAsync());
        }

        // GET: Korisniks/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korisnik = await _context.Korisnik
                .FirstOrDefaultAsync(m => m.Id == id);
            if (korisnik == null)
            {
                return NotFound();
            }

            return View(korisnik);
        }

        // GET: Korisniks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Korisniks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Surname,JMBAG")] Korisnik korisnik)
        {
            if (ModelState.IsValid)
            {
                _context.Add(korisnik);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(korisnik);
        }

        // GET: Korisniks/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korisnik = await _context.Korisnik.FindAsync(id);
            if (korisnik == null)
            {
                return NotFound();
            }
            return View(korisnik);
        }

        // POST: Korisniks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,Surname,JMBAG")] Korisnik korisnik)
        {
            if (id != korisnik.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(korisnik);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KorisnikExists(korisnik.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(korisnik);
        }

        // GET: Korisniks/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korisnik = await _context.Korisnik
                .FirstOrDefaultAsync(m => m.Id == id);
            if (korisnik == null)
            {
                return NotFound();
            }

            return View(korisnik);
        }

        // POST: Korisniks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var korisnik = await _context.Korisnik.FindAsync(id);
            _context.Korisnik.Remove(korisnik);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KorisnikExists(string id)
        {
            return _context.Korisnik.Any(e => e.Id == id);
        }
    }
}

Views/ClassAttends/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model List<Studenti.Controllers.ClassAttendsController.DisplayAttend>

@{
    ViewData["Title"] = "Index";
}


@inject SignInManager<Korisnik> SignInManager
@inject UserManager<Korisnik> UserManager

<style>
    .dropbtn {
        background-color: #4CAF50;
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;
    }

    .dropdown {
        position: relative;
        display: inline-block;
    }

    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 60px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }

        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

            .dropdown-content a:hover {
                background-color: #ddd;
            }

    .dropdown:hover .dropdown-content {
        display: block;
    }

    .dropdown:hover .dropbtn {
        background-color: #3e8e41;
    }
</style>

<h2>Attend class</h2>

<form asp-action="Create">


    <div class="form-group">

        <input type="submit" value="Attend" class="btn btn-default" />
    </div>
</form>

<form asp-controller="Korisniks" asp-action="Index">

    <div class="form-actions no-color">

        <p style="margin-top:20px">
            <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <input type="submit" value="Search" class="btn btn-outline-success btn-sm" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>

        <tr>
            <th>
                JMBAG
            </th>
            <th>
                Ime
            </th>
            <th>
                Prezime
            </th>
            <th>
                Logged Time
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.JMBAG)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)

                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.LoggedTime)
                </td>

            </tr>
        }
    </tbody>
</table>