Models/Korisnik.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Studenti.Models;

namespace Studenti.Models
{
    public class Korisnik : IdentityUser

    {
        [MaxLength(36)]
        public string Email { get; set; }
        [MaxLength(50)]
        public string Name { get; set; }
        [MaxLength(50)]
        public string Surname { get; set; }
        [MaxLength(10)]
        public string JMBAG { get; set; }
       
       
    




    }
}
//In Visual Studio, use the Package Manager Console to scaffold a new migration for these changes and apply them to the database:
//PM> Add-Migration[migration name]
//PM> Update-Database
//Alternatively, you can scaffold a new migration and apply it from a command prompt at your project directory:
//> dotnet ef migrations add[migration name]
//> dotnet ef database update 

Controllers/ClassAttendsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Studenti.Data;
using Studenti.Models;
using Studenti.Utility;

namespace Studenti.Controllers
{
    public class ClassAttendsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Korisnik> _userManager;

        public class DisplayAttend
        {
            public string JMBAG { get; set; }
            public DateTime LoggedTime { get; set; }

            public string Name { get; set; }
            public string Surname { get; set; }


         
            public DisplayAttend()
            {

            }

            public DisplayAttend(string name, string surname, string jMBAG, DateTime loggedTime )
            {
                JMBAG = jMBAG;
                Name = name;
                Surname = surname;
                LoggedTime = loggedTime;
             
         
            }

           
          

            
        }

        public ClassAttendsController(ApplicationDbContext context, UserManager<Korisnik> userManager)
        {
            _context = context;
            _userManager = userManager;
          
          
        }


      


        // GET: ClassAttends
        public async Task<IActionResult> Index()
        {
           var UserList = await _userManager.Users.ToListAsync();
            var currentUser = await _userManager.GetUserAsync(User);
            bool isStudent = await _userManager.IsInRoleAsync(currentUser, StaticDetails.StudentRole);
            List<ClassAttend> classAttends = null;
            
            if (isStudent)
            {   
                classAttends = await _context.ClassAttends.Where(ca => ca.IdentityUserId == currentUser.Id).ToListAsync();
               
               
            }
            else {

                classAttends = await _context.ClassAttends.ToListAsync();
            }

           List<DisplayAttend> data = new List<DisplayAttend>();

            foreach (ClassAttend ca in classAttends)
            {
                data.Add(new DisplayAttend(UserList.FirstOrDefault(u => u.Id == ca.IdentityUserId).Name, UserList.FirstOrDefault (u=> u.Id == ca.IdentityUserId).Surname, UserList.FirstOrDefault(u => u.Id == ca.IdentityUserId).JMBAG, ca.LoggedTime));


            }
            
            return View(data);
        }

        // POST: ClassAttends/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string t)
        {

            var currentUser = await _userManager.GetUserAsync(User);

            ClassAttend classAttend = new ClassAttend(currentUser.Id, currentUser.Name, currentUser.Surname, DateTime.Now);

            if (ModelState.IsValid)
            {
                _context.Add(classAttend);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(classAttend);
        }


       
    }
    }

Controllers/KorisniksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Studenti.Data;
using Studenti.Models;
using Studenti.Controllers;

namespace Studenti.Controllers
{
    public class KorisniksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public KorisniksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Korisniks
        public async Task<IActionResult> Index(string searchString)

        {
           
            ViewData["CurrentFilter"] = searchString;

         
            var li = from s in _context.Korisnik
                     select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                li = li.Where(s => s.Name.Contains(searchString)
                                       || s.Surname.Contains(searchString));
            }

           
        
            return View(await li.AsNoTracking().ToListAsync());
        }

        // GET: Korisniks/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korisnik = await _context.Korisnik
                .FirstOrDefaultAsync(m => m.Id == id);
            if (korisnik == null)
            {
                return NotFound();
            }

            return View(korisnik);
        }

        // GET: Korisniks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Korisniks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Surname,JMBAG")] Korisnik korisnik)
        {
            if (ModelState.IsValid)
            {
                _context.Add(korisnik);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(korisnik);
        }

        // GET: Korisniks/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korisnik = await _context.Korisnik.FindAsync(id);
            if (korisnik == null)
            {
                return NotFound();
            }
            return View(korisnik);
        }

        // POST: Korisniks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,Surname,JMBAG")] Korisnik korisnik)
        {
            if (id != korisnik.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(korisnik);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KorisnikExists(korisnik.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(korisnik);
        }

        // GET: Korisniks/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var korisnik = await _context.Korisnik
                .FirstOrDefaultAsync(m => m.Id == id);
            if (korisnik == null)
            {
                return NotFound();
            }

            return View(korisnik);
        }

        // POST: Korisniks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var korisnik = await _context.Korisnik.FindAsync(id);
            _context.Korisnik.Remove(korisnik);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KorisnikExists(string id)
        {
            return _context.Korisnik.Any(e => e.Id == id);
        }
    }
}

Views/Korisniks/Create.cshtml
@model Studenti.Models.Korisnik

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Korisnik</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JMBAG" class="control-label"></label>
                <input asp-for="JMBAG" class="form-control" />
                <span asp-validation-for="JMBAG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Korisniks/Delete.cshtml
@model Studenti.Models.Korisnik

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Korisnik</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.JMBAG)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.JMBAG)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Korisniks/Details.cshtml
@model Studenti.Models.Korisnik

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Korisnik</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.JMBAG)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.JMBAG)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Korisniks/Edit.cshtml
@model Studenti.Models.Korisnik

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Korisnik</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JMBAG" class="control-label"></label>
                <input asp-for="JMBAG" class="form-control" />
                <span asp-validation-for="JMBAG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Korisniks/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using Studenti.Models
@model IEnumerable<Studenti.Models.Korisnik>

@{
    ViewData["Title"] = "Search";
}

<h2>Search</h2>


<form asp-action="Index" method="get" >

    <div class="form-actions no-color">

        <p style="margin-top:20px">
            <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <input type="submit" value="Search" class="btn btn-outline-success btn-sm" /> |
            <a asp-controller="ClassAttends" asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>

        <tr>
            <th>
                JMBAG
            </th>
            <th>
                Ime
            </th>
            <th>
                Prezime
            </th>
          

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.JMBAG)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
           </td>
            
        



        </tr>
        }
    </tbody>
</table>